networks:
  default:
  traefik:
    external: true

services:
  pretix:
    image: pretix/standalone:stable
    restart: unless-stopped
    depends_on:
      - pretix-db
      - pretix-redis
    volumes:
      - ./volumes/data:/data
      - ./generated/pretix.cfg:/etc/pretix/pretix.cfg
    # ports:
    #   - "8000:80"
    networks:
      - traefik
      - default

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pretix.rule=Host(`${EXAMPLE_DOMAIN}`)"
      - "traefik.http.routers.pretix.entrypoints=websecure"

  pretix-db:
    image: postgres:13-alpine3.19
    restart: unless-stopped
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=pretix
    volumes:
      - ./volumes/db:/var/lib/postgresql/data

  pretix-redis:
    image: redis:alpine3.19
    restart: unless-stopped
    # ports:
    #   - "6379:6379"
