networks:
  default:
  traefik:
    external: true

services:
  pretix:
    ${PRETIX_SOURCE}
    restart: unless-stopped
    depends_on:
      - pretix-db
      - pretix-redis
    volumes:
      - ./volumes/data:/data
      - ./volumes/pretix:/etc/pretix
      - ./generated/pretix.cfg:/etc/pretix/pretix.cfg
    # ports:
    #   - "8000:80"
    networks:
      - traefik
      - default

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pretix.rule=Host(\`${PRETIX_DOMAIN}\`)"
      - "traefik.http.routers.pretix.entrypoints=websecure"
      - "traefik.http.middlewares.pretix-ratelimit.ratelimit.average=100"
      - "traefik.http.middlewares.pretix-ratelimit.ratelimit.burst=30"
      - "traefik.http.middlewares.pretix-ratelimit.ratelimit.period=1m"
      - "traefik.http.routers.pretix.middlewares=pretix-ratelimit"

  pretix-db:
    image: postgres:13-alpine3.19
    restart: unless-stopped
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=${PRETIX_DB_PASSWORD}
      - POSTGRES_DB=pretix
    volumes:
      - ./volumes/db:/var/lib/postgresql/data

  pretix-redis:
    image: redis:alpine3.19
    restart: unless-stopped
    # ports:
    #   - "6379:6379"
